#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/scripts/venv.sh"
set_venv_python "$root_dir/tools"

dotnet restore
"$VENV_PY" -m pip install -r "$root_dir/tools/requirements.txt"
