### Get draw results | default parameters
GET http://localhost:7163/api/draw-results

### Get draw results | top=12
GET http://localhost:7163/api/draw-results?top=12

### Get draw results | top=1000
GET http://localhost:7163/api/draw-results?top=1000

### Get draw results | top=1500
GET http://localhost:7163/api/draw-results?top=1500

### Get draw results | dateFrom=2025-01-01
GET http://localhost:7163/api/draw-results?dateFrom=2025-01-01

### Get draw results | dateFrom=2025-01-01, dateTo=2025-01-20
GET http://localhost:7163/api/draw-results?dateFrom=2025-01-01&dateTo=2025-01-20

### Get draw results | dateTo=2012-01-01, top=10
GET http://localhost:7163/api/draw-results?dateTo=2012-01-01&top=10

### Get draw results | dateFrom=2025-01-01, dateTo=2025-01-20, top=2
GET http://localhost:7163/api/draw-results?dateFrom=2025-01-01&dateTo=2025-01-20&top=2

### Get draw results | dateFrom=2012-01-01
GET http://localhost:7163/api/draw-results?dateFrom=2012-01-01

### Get draw results | dateFrom=2000-01-01
GET http://localhost:7163/api/draw-results?dateFrom=2000-01-01


### Download draw results | default parameters
GET http://localhost:7163/api/draw-results
Accept: application/octet-stream

### Download draw results | top=12
GET http://localhost:7163/api/draw-results?top=12
Accept: application/octet-stream

### Download draw results | dateFrom=2025-01-01
GET http://localhost:7163/api/draw-results?dateFrom=2025-01-01
Accept: application/octet-stream


### Drop draw results table
DELETE http://localhost:7163/api/draw-results-table
