### Get draw results | default parameters
GET http://localhost:7163/api/draw-results

### Get draw results | top=10
GET http://localhost:7163/api/draw-results?top=10

### Get draw results | dateFrom=2024-01-01, dateTo=2025-01-01, top=10
GET http://localhost:7163/api/draw-results?dateFrom=2024-01-01&dateTo=2025-01-01&top=10


### Download draw results | default parameters
GET http://localhost:7163/api/draw-results
Accept: application/octet-stream

### Download draw results | top=10
GET http://localhost:7163/api/draw-results?top=10
Accept: application/octet-stream

### Download draw results | dateFrom=2025-01-01
GET http://localhost:7163/api/draw-results?dateFrom=2025-01-01
Accept: application/octet-stream


### Create draw results table
POST http://localhost:7163/api/draw-results-table

### Drop draw results table
DELETE http://localhost:7163/api/draw-results-table
